name: CheckPackage
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          max-parallel: 5
          fail-fast: true
          matrix:
            python-version: [3.6, 3.7, 3.8]
        steps:
            - uses: actions/checkout@master
            - name: Setup Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install Poetry
              uses: snok/install-poetry@v1.1.1
              with:
                virtualenvs-create: true
                virtualenvs-in-project: true
              #----------------------------------------------
              #       load cached venv if cache exists
              #----------------------------------------------
            - name: Load cached venv
              id: cached-poetry-dependencies
              uses: actions/cache@v2
              with:
                path: .venv
                key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
              # with:
              #   version: 1.0.0b3
            # - name: Turn off Virtualenvs
            #   run: poetry config virtualenvs.create false
            - name: Install packages
              run: poetry install
              if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
            - name: Run PyTest
              run: |
                source .venv/bin/activate
                pytest tests/
            # - name: Run mypy
            #   run: poetry run mypy pyservos
            # - name: nosetests
            #   run: |
            #     pip install nose
            #     cd python
            #     python -m pip install -e .
            #     cd tests
            #     nosetests -vs test.py
            # - name: Python Style Checker
            #   uses: andymckay/pycodestyle-action@0.1.3
